### ISSUE TITLE
Should I use TCP/IP or Serial

### ISSUE THREAD

**Issue by abdulfhussain** [themainframe/homebridge-texecom-connect#2]
Please bear with me as I am new to this.  I have a Texecom Premier 88 alarm system and have  SMARTCOM installed so that 1) I can use the Texecom Connect App and 2) I can add a dialer so that it rings me if the alarm is triggered.

i am trying to setup your homebridge plugin, I tried using the TCP/IP and used the IP address of the Texecom device I could see on my network but this did not seem to work. Do I need to change anything else in order to use the IP address?

I am not sure where to get the Serial for my alarm from. Would using Serial be a better option for me?

Is there any other configuration I need to do (apart from adding the zones)?

Thanks in advance

**Comment by themainframe** [comment]
I think Serial is generally more reliable, but you'd have to run Homebridge on something close to the panel (maybe a Raspberry Pi?). As for obtaining a cable, you could buy a commercial one, or use a custom setup like the one detailed here - https://cybergibbons.com/alarms-2/programming-a-texecom-premier-elite-12-w-using-a-ftdi-cable/

If you want to use TCP/IP, I wouldn't recommend using the SmartCom as it'll prevent any other connections to the panel. You're best buying a ComIP or ComWiFi (now deprecated but available on eBay I believe). I'd check that whatever communicator you want to use is working using Wintex first before setting up `homebridge-texecom-connect` too.

**Comment by abdulfhussain** [comment]
Thank you for the quick reply. All this seems outside of my comfort zone, I am running homebridge on my NAS which is not near the alarm. I can already control the alarm remotely through the Texecom Connect app so I think I will leave it for now.

Really appreciate you getting back to me so quickly.
